
import { BeCampaignDetails, EnergyPlan, LocationFromZipCode } from './interfaces-energy';

export const ENERGY_PLANS: EnergyPlan[] = [
    {
        index: 7,
        sysId: 55880,
        utility: "Eversource - WMECO",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "MA",
        initialRate: 19.9,
        rateUnit: "kWh",
        rateCode: "WMECO-EL_NA_INTMONFEBR_02_ALL_000_N100_XX",
        utilityId: "WMEC",
        utilityPublicName: "Eversource",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.1581,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        },
        zipCode: '02114',
    },
    {
        index: 13,
        sysId: 55876,
        utility: "National Grid",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "MA",
        initialRate: 21.9,
        rateUnit: "kWh",
        rateCode: "NGRDMECO_NA_INTMONFEBR_02_ALL_000_N100_XX",
        utilityId: "MECO",
        utilityPublicName: "National Grid",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.18213,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        },
        zipCode: '02114',
    },
    {
        index: 14,
        sysId: 55877,
        utility: "Eversource  - NStar BECO",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "MA",
        initialRate: 21.9,
        rateUnit: "kWh",
        zipCode: "02114",
        utilityPublicName: "Eversource",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.17216,
        rateCode: "NSTARBEC_NA_INTMONFEBR_02_ALL_000_N100_XX",
        utilityId: "BECO",
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        }
    },
    {
        index: 11,
        sysId: 55875,
        utility: "Delmarva DE",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "DE",
        initialRate: 8.99,
        rateUnit: "kWh",
        rateCode: "DELMRVDE_NA_INTMONFEBR_02_ALL_000_N100_XX",
        utilityId: "DELDEE",
        zipCode: "19904",
        utilityPublicName: "Delmarva DE",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.10751,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        }
    },
    {
        index: 6,
        sysId: 55926,
        utility: "Delmarva DE",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 12,
        termLength: 12,
        termType: "Fixed",
        state: "DE",
        initialRate: 15.7,
        rateUnit: "kWh",
        zipCode: "19904",
        rateCode: "DELMRVDE_NA_FIX015700R_12_WEB_000_N100_XX",
        utilityId: "DELDEE",
        utilityPublicName: "Delmarva DE",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.10751,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        }
    },
    {
        index: 7,
        sysId: 55927,
        utility: "Delmarva DE",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 6,
        termLength: 6,
        termType: "Fixed",
        state: "DE",
        initialRate: 15.08,
        rateUnit: "kWh",
        zipCode: "19904",
        rateCode: "DELMRVDE_NA_FIX015080R_06_WEB_000_N100_XX",
        utilityId: "DELDEE",
        utilityPublicName: "Delmarva DE",
        utillityRateValue: 0.10751,
        displayName: "Web Green Fixed",
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        }
    },
 {
        index: 24,
        sysId: 55868,
        utility: "People's Equitable Gas",
        commodityType: "G",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "PA",
        rateUnit: "Mcf",
        zipCode: "15290",
        rateCode: "EQUITBLE_NA_INTMONFEBR_02_ALL_000_N100_FP",
        utilityId: "EQTG",
        utilityPublicName: "People's Equitable Gas",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 2.5214,
        initialRate: 200,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "HW36229PR": "CINCH Home Services Surge Protection Plan Included"
        }
    },
    {
        index: 25,
        sysId: 55894,
        utility: "Duquesne Light",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "PA",
        initialRate: 8.9,
        rateUnit: "kWh",
        zipCode: "15290",
        rateCode: "DUQUESNE_NA_INTMONFEBR_02_ALL_000_N100_XX",
        utilityId: "DUQ",
        utilityPublicName: "Duquesne",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.10455,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP50D": "$50 in VISA Gift Card Welcome Rewards",
            "HW38970PR": "CINCH Home Services Line & Surge Protection Plan Included"
        }
    },
    {
        index: 7,
        sysId: 56057,
        utility: "Duquesne Light",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 12,
        termLength: 12,
        termType: "Fixed",
        state: "PA",
        rateUnit: "kWh",
        zipCode: "15290",
        rateCode: "DUQUESNE_NA_FIX015380R_12_WEB_000_N100_XX",
        utilityId: "DUQ",
        utilityPublicName: "Duquesne",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.10455,
        initialRate: 15.38,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP50D": "$50 in VISA Gift Card Welcome Rewards"
        }
    },
    {
        index: 8,
        sysId: 56058,
        utility: "Duquesne Light",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 6,
        termLength: 6,
        termType: "Fixed",
        state: "PA",
        initialRate: 14.98,
        rateUnit: "kWh",
        zipCode: "15290",
        rateCode: "DUQUESNE_NA_FIX014980R_06_WEB_000_N100_XX",
        utilityId: "DUQ",
        utilityPublicName: "Duquesne",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.10455,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP50D": "$50 in VISA Gift Card Welcome Rewards"
        }
    },
    {
        index: 16,
        sysId: 56183,
        utility: "People's Equitable Gas",
        commodityType: "G",
        rateType: "Web Green Fixed",
        initialTerm: 12,
        termLength: 12,
        termType: "Fixed",
        state: "PA",
        initialRate: 1106.9,
        rateUnit: "Mcf",
        zipCode: "15290",
        rateCode: "EQUITBLE_NA_FIX110690R_12_WEB_000_N100_FP",
        utilityId: "EQTG",
        utilityPublicName: "People's Equitable Gas",
        displayName: "Web Green Fixed",
        utillityRateValue: 2.5214,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars"
        }
    },
    {
        index: 17,
        sysId: 56184,
        utility: "People's Equitable Gas",
        commodityType: "G",
        rateType: "Web Green Fixed",
        initialTerm: 6,
        termLength: 6,
        termType: "Fixed",
        state: "PA",
        initialRate: 994,
        rateUnit: "Mcf",
        zipCode: "15290",
        rateCode: "EQUITBLE_NA_FIX099400R_06_WEB_000_N100_FP",
        utilityId: "EQTG",
        utilityPublicName: "People's Equitable Gas",
        displayName: "Web Green Fixed",
        utillityRateValue: 2.5214,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars"
        }
    },
 {
        index: 23,
        sysId: 55858,
        utility: "BGE - Baltimore Gas and Electric",
        commodityType: "G",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "MD",
        initialRate: 41.9,
        rateUnit: "therm",
        zipCode: "21223",
        rateCode: "BGE-NGAS_NA_INTMONFEBR_02_ALL_000_N100_XX",
        utilityId: "BGE",
        utilityPublicName: "BGE",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.518,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars"
        }
    },
    {
        index: 24,
        sysId: 55882,
        utility: "BGE - Baltimore Gas and Electric",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "MD",
        initialRate: 10.4,
        rateUnit: "kWh",
        zipCode: "21223",
        rateCode: "BGE-ELEC_NA_INTMONFEBR_02_ALL_000_N100_XX",
        utilityId: "BGE",
        utilityPublicName: "BGE",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.11154,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP50D": "$50 in VISA Gift Card Welcome Rewards"
        }
    },
    {
        index: 6,
        sysId: 55975,
        utility: "BGE - Baltimore Gas and Electric",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 12,
        termLength: 12,
        termType: "Fixed",
        state: "MD",
        initialRate: 17.23,
        rateUnit: "kWh",
        zipCode: "21223",
        rateCode: "BGE-ELEC_NA_FIX017230R_12_WEB_000_N100_XX",
        utilityId: "BGE",
        utilityPublicName: "BGE",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.11154,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP50D": "$50 in VISA Gift Card Welcome Rewards"
        }
    },
    {
        index: 7,
        sysId: 55976,
        utility: "BGE - Baltimore Gas and Electric",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 6,
        termLength: 6,
        termType: "Fixed",
        state: "MD",
        initialRate: 16.74,
        rateUnit: "kWh",
        zipCode: "21223",
        rateCode: "BGE-ELEC_NA_FIX016740R_06_WEB_000_N100_XX",
        utilityId: "BGE",
        utilityPublicName: "BGE",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.11154,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP50D": "$50 in VISA Gift Card Welcome Rewards"
        }
    },
    {
        index: 15,
        sysId: 56113,
        utility: "BGE - Baltimore Gas and Electric",
        commodityType: "G",
        rateType: "Web Green Fixed",
        initialTerm: 12,
        termLength: 12,
        termType: "Fixed",
        state: "MD",
        initialRate: 113.81,
        rateUnit: "therm",
        zipCode: "21223",
        rateCode: "BGE-NGAS_NA_FIX113810R_12_WEB_000_N100_XX",
        utilityId: "BGE",
        utilityPublicName: "BGE",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.518,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars"
        }
    },
    {
        index: 16,
        sysId: 56114,
        utility: "BGE - Baltimore Gas and Electric",
        commodityType: "G",
        rateType: "Web Green Fixed",
        initialTerm: 6,
        termLength: 6,
        termType: "Fixed",
        state: "MD",
        initialRate: 121.97,
        rateUnit: "therm",
        zipCode: "21223",
        rateCode: "BGE-NGAS_NA_FIX121970R_06_WEB_000_N100_XX",
        utilityId: "BGE",
        utilityPublicName: "BGE",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.518,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars"
        }
    },
 {
        index: 39,
        sysId: 55862,
        utility: "NJNG - New Jersey Natural Gas",
        commodityType: "G",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "NJ",
        initialRate: 34,
        rateUnit: "therm",
        rateCode: "NJNTLGAS_NA_INTMONFEBR_02_ALL_DSC_N100_XX",
        utilityId: "NJNG",
        utilityPublicName: "New Jersey Natural Gas",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.429,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "HW36229PR": "CINCH Home Services Surge Protection Plan Included"
        },
        zipCode: '08701',
    },
    {
        index: 40,
        sysId: 55886,
        utility: "JCP&L - Jersey Central Power and Light",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "NJ",
        initialRate: 8.4,
        rateUnit: "kWh",
        zipCode: "08701",
        rateCode: "JCPLELEC_NA_INTMONFEBR_02_ALL_DSC_N100_XX",
        utilityId: "JCPL",
        utilityPublicName: "JCP&L",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.09852,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward",
            "HW38970PR": "CINCH Home Services Line & Surge Protection Plan Included"
        }
    },
    {
        index: 41,
        sysId: 55887,
        utility: "PSEG - Public Service Electric and Gas",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "NJ",
        initialRate: 12.4,
        rateUnit: "kWh",
        zipCode: "08701",
        rateCode: "PSEG-ELE_NA_INTMONFEBR_02_ALL_DSC_N100_XX",
        utilityId: "PSEG",
        utilityPublicName: "PSEG",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.13771,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward",
            "HW38970PR": "CINCH Home Services Line & Surge Protection Plan Included"
        }
    },
    {
        index: 42,
        sysId: 55890,
        utility: "JCP&L - Jersey Central Power and Light",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "NJ",
        initialRate: 8.4,
        rateUnit: "kWh",
        zipCode: "08701",
        rateCode: "JCPLELEC_NA_INTMONFEBR_02_ALL_COO_N100_XX",
        utilityId: "JCPL",
        utilityPublicName: "JCP&L",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.09852,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward",
            "HW38970PR": "CINCH Home Services Line & Surge Protection Plan Included"
        }
    },
    {
        index: 43,
        sysId: 55891,
        utility: "PSEG - Public Service Electric and Gas",
        commodityType: "E",
        rateType: "Green Variable",
        initialTerm: 2,
        termLength: 2,
        termType: "Variable",
        state: "NJ",
        initialRate: 12.4,
        rateUnit: "kWh",
        zipCode: "08701",
        rateCode: "PSEG-ELE_NA_INTMONFEBR_02_ALL_COO_N100_XX",
        utilityId: "PSEG",
        utilityPublicName: "PSEG",
        displayName: "February 2024 Intro Rate",
        utillityRateValue: 0.13771,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward",
            "HW38970PR": "CINCH Home Services Line & Surge Protection Plan Included"
        }
    },
    {
        index: 7,
        sysId: 56014,
        utility: "JCP&L - Jersey Central Power and Light",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 12,
        termLength: 12,
        termType: "Fixed",
        state: "NJ",
        initialRate: 16.84,
        rateUnit: "kWh",
        zipCode: "08701",
        rateCode: "JCPLELEC_NA_FIX016840R_12_WEB_000_N100_XX",
        utilityId: "JCPL",
        utilityPublicName: "JCP&L",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.09852,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        }
    },
    {
        index: 8,
        sysId: 56015,
        utility: "JCP&L - Jersey Central Power and Light",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 6,
        termLength: 6,
        termType: "Fixed",
        state: "NJ",
        initialRate: 15.98,
        rateUnit: "kWh",
        zipCode: "08701",
        rateCode: "JCPLELEC_NA_FIX015980R_06_WEB_000_N100_XX",
        utilityId: "JCPL",
        utilityPublicName: "JCP&L",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.09852,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        }
    },
    {
        index: 18,
        sysId: 56025,
        utility: "PSEG - Public Service Electric and Gas",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 12,
        termLength: 12,
        termType: "Fixed",
        state: "NJ",
        initialRate: 19.04,
        rateUnit: "kWh",
        zipCode: "08701",
        rateCode: "PSEG-ELE_NA_FIX019040R_12_WEB_000_N100_XX",
        utilityId: "PSEG",
        utilityPublicName: "PSEG",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.13771,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        }
    },
    {
        index: 19,
        sysId: 56026,
        utility: "PSEG - Public Service Electric and Gas",
        commodityType: "E",
        rateType: "Web Green Fixed",
        initialTerm: 6,
        termLength: 6,
        termType: "Fixed",
        state: "NJ",
        initialRate: 17.98,
        rateUnit: "kWh",
        zipCode: "08701",
        rateCode: "PSEG-ELE_NA_FIX017980R_06_WEB_000_N100_XX",
        utilityId: "PSEG",
        utilityPublicName: "PSEG",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.13771,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars",
            "RP25D": "$25/25 Welcome Reward"
        }
    },
    {
        index: 28,
        sysId: 56141,
        utility: "NJNG - New Jersey Natural Gas",
        commodityType: "G",
        rateType: "Web Green Fixed",
        initialTerm: 12,
        termLength: 12,
        termType: "Fixed",
        state: "NJ",
        initialRate: 124.27,
        rateUnit: "therm",
        zipCode: "08701",
        rateCode: "NJNTLGAS_NA_FIX124270R_12_WEB_000_N100_XX",
        utilityId: "NJNG",
        utilityPublicName: "New Jersey Natural Gas",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.429,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars"
        }
    },
    {
        index: 29,
        sysId: 56142,
        utility: "NJNG - New Jersey Natural Gas",
        commodityType: "G",
        rateType: "Web Green Fixed",
        initialTerm: 6,
        termLength: 6,
        termType: "Fixed",
        state: "NJ",
        initialRate: 103.72,
        rateUnit: "therm",
        zipCode: "08701",
        rateCode: "NJNTLGAS_NA_FIX103720R_06_WEB_000_N100_XX",
        utilityId: "NJNG",
        utilityPublicName: "New Jersey Natural Gas",
        displayName: "Web Green Fixed",
        utillityRateValue: 0.429,
        incentivePublicNotes: {
            "RP50PT": "50 MyEnergyPerks® Dollars"
        }
    }
]

export const STATE_FROM_ZIP_CODE_RESPONSES: LocationFromZipCode[] = [
    {
        "ZipCode": "08701",
        "City": "Lakewood",
        "State": "NJ",
        "County": "Burlington",
        "CreatedBy": '',
        "DateCreated": '',
        "UpdatedBy": '',
        "LastUpdated": '',
        "Cncount": 3,
        "CountyList": "Burlington,Monmouth,Ocean",
        "City2": '',
        "SysId": 19924
    },
    {
        "ZipCode": "48138",
        "City": "Grosse Ile",
        "State": "MI",
        "County": "Oakland",
        "CreatedBy": '',
        "DateCreated": '',
        "UpdatedBy": '',
        "LastUpdated": '',
        "Cncount": 2,
        "CountyList": "Oakland,Wayne",
        "City2": "Grosse Ile",
        "SysId": 33772
    },

    {
        "ZipCode": "19904",
        "City": "Dover",
        "State": "DE",
        "County": "Kent",
        "CreatedBy": '',
        "DateCreated": '',
        "UpdatedBy": '',
        "LastUpdated": '',
        "Cncount": 3,
        "CountyList": "Kent,New Castle,Sussex",
        "City2": '',
        "SysId": 7242
    },

    {
        "ZipCode": "02114",
        "City": "Boston",
        "State": "MA",
        "County": "Suffolk",
        "CreatedBy": '',
        "DateCreated": '',
        "UpdatedBy": '',
        "LastUpdated": '',
        "Cncount": 4,
        "CountyList": "Essex,Middlesex,Norfolk,Suffolk",
        "City2": '',
        "SysId": 793
    },

    {
        "ZipCode": "21223",
        "City": "Baltimore",
        "State": "MD",
        "County": "Baltimore City",
        "CreatedBy": '',
        "DateCreated": '',
        "UpdatedBy": '',
        "LastUpdated": '',
        "Cncount": 2,
        "CountyList": "Baltimore,Baltimore City",
        "City2": '',
        "SysId": 7079
    },


    {
        "ZipCode": "15290",
        "City": "Pittsburgh",
        "State": "PA",
        "County": "Allegheny",
        "CreatedBy": '',
        "DateCreated": '',
        "UpdatedBy": '',
        "LastUpdated": '',
        "Cncount": 1,
        "CountyList": "Allegheny",
        "City2": '',
        "SysId": 10028
    }
];

export const CAMPAIGN_DETAILS_RESP: BeCampaignDetails = 

{
    "CampaignCode": "VRNJ-103",
    "StartDate": "2023-05-22T00:00:00",
    "EndDate": "2024-12-31T00:00:00",
    "Channel": "Generic",
    "CampaignType": "All",
    "CommunicationVehicle": "VR",
    "Market": "NJ",
    "MarketList": '',
    "RevenueClass": "Residential",
    "RateType": "Fixed,InitialToFixed,IntroToVariable,Variable",
    "Commodity": "Electric",
    "Notes": "Capital One Electric Offers",
    "Description": "Generic Various Campaign for States: NJ for Territories: All",
    "CampaignURL": '',
    "Territory": '',
    "RateList": [
        {
            "Utility": "ACE - Atlantic City Electric",
            "CommodityType": "E",
            "RateType": "Internal Green Fixed",
            "TaxRate": "RES",
            "State": "NJ",
            "RateCode": "ATLNCITY_NA_FIX013830R_12_ISC_000_N100_XX",
            "UtilityId": "ACE",
            "AccountNumberPattern": "^(\\d{22})$",
            "AccountNumberDescription": "22 Digit Service Agreement Number",
            "AccountNumberDescriptionSpanish": "Número de acuerdo de servicio de 22 dígitos",
            "AccountNumberLabel": "Service Agreement Number",
            "UtilityPublicName": "Atlantic City Electric",
            "RateCodeType": "ISC_N_R_FIX",
            "TerritoryId": "ACE",
            "EnableForWebOverride": false,
            "ShowBudget": true,
            "UsageLimit": 0,
            "DailyRateValue": 0,
            "FlatRateValue": 0,
            "Index": 11,
            "SysId": 56007,
            "TerritorySysId": 21,
            "UtilityRateTypeSysId": 0,
            "InitialRate": 13.83,
            "InitialTerm": 12,
            "EnrollmentFee": 0,
            "CancellationFee": 0,
            "SecondaryRate": 0,
            "SecondaryTerm": 0,
            "MidRate": 0,
            "TotalTerm": 0,
            "TermLength": 12,
            "TermType": "Fixed",
            "Language": '',
            "Phone": "(800) 642-3780",
            "RateUnit": "kWh",
            "Budget": "Not available",
            "BudgetText": "Indra Energy does not offer Budget Billing in your area. If you are interested in Budget Billing, please contact your utility company.",
            "PtcUtil": '',
            "PtcRate": 0,
            "PtcRateLow": 0,
            "PtcRateHigh": 0,
            "PtcStartDate": '',
            "PtcEndDate": '',
            "TodayDate": "03/08/2024",
            "PublicName": ''
        },
        {
            "Utility": "JCP&L - Jersey Central Power and Light",
            "CommodityType": "E",
            "RateType": "Internal Green Fixed",
            "TaxRate": "RES",
            "State": "NJ",
            "RateCode": "JCPLELEC_NA_FIX012790R_12_ISC_000_N100_XX",
            "UtilityId": "JCPL",
            "AccountNumberPattern": "^(080\\d{17})$",
            "AccountNumberDescription": "20 Digit Customer Number. Begins with 080.",
            "AccountNumberDescriptionSpanish": "Número de cliente de 20 dígitos. Empieza por 080.",
            "AccountNumberLabel": "Customer Number",
            "UtilityPublicName": "JCP&L",
            "RateCodeType": "ISC_N_R_FIX",
            "TerritoryId": "JCPLE",
            "EnableForWebOverride": false,
            "ShowBudget": true,
            "UsageLimit": 0,
            "DailyRateValue": 0,
            "FlatRateValue": 0,
            "Index": 22,
            "SysId": 56018,
            "TerritorySysId": 33,
            "UtilityRateTypeSysId": 0,
            "InitialRate": 12.79,
            "InitialTerm": 12,
            "EnrollmentFee": 0,
            "CancellationFee": 0,
            "SecondaryRate": 0,
            "SecondaryTerm": 0,
            "MidRate": 0,
            "TotalTerm": 0,
            "TermLength": 12,
            "TermType": "Fixed",
            "Language": '',
            "Phone": "(800) 662-3115",
            "RateUnit": "kWh",
            "Budget": "In house",
            "BudgetText": "I would like to participate in budget billing for my [electric_gas] supply charges.",
            "PtcUtil": '',
            "PtcRate": 0,
            "PtcRateLow": 0,
            "PtcRateHigh": 0,
            "PtcStartDate": '',
            "PtcEndDate": '',
            "TodayDate": "03/08/2024",
            "PublicName": ''
        },
        {
            "Utility": "PSEG - Public Service Electric and Gas",
            "CommodityType": "E",
            "RateType": "Internal Green Fixed",
            "TaxRate": "RES",
            "State": "NJ",
            "RateCode": "PSEG-ELE_NA_FIX014990R_12_ISC_000_N100_XX",
            "UtilityId": "PSEG",
            "AccountNumberPattern": "^(PE\\d{18})$",
            "AccountNumberDescription": "20 Digit POD ID Number. Electric begins with PE. (E.G PE123456789012345678)",
            "AccountNumberDescriptionSpanish": "Número de identificación del POD de 20 dígitos. Electric comienza con PE. (Por ejemplo, PE123456789012345678)",
            "AccountNumberLabel": "POD ID Number",
            "UtilityPublicName": "PSEG",
            "RateCodeType": "ISC_N_R_FIX",
            "TerritoryId": "PSEGE",
            "EnableForWebOverride": false,
            "ShowBudget": true,
            "UsageLimit": 0,
            "DailyRateValue": 0,
            "FlatRateValue": 0,
            "Index": 33,
            "SysId": 56029,
            "TerritorySysId": 42,
            "UtilityRateTypeSysId": 0,
            "InitialRate": 14.99,
            "InitialTerm": 12,
            "EnrollmentFee": 0,
            "CancellationFee": 0,
            "SecondaryRate": 0,
            "SecondaryTerm": 0,
            "MidRate": 0,
            "TotalTerm": 0,
            "TermLength": 12,
            "TermType": "Fixed",
            "Language": '',
            "Phone": "(800) 436-7734",
            "RateUnit": "kWh",
            "Budget": "In house",
            "BudgetText": "I would like to participate in budget billing for my [electric_gas] supply charges.",
            "PtcUtil": '',
            "PtcRate": 0,
            "PtcRateLow": 0,
            "PtcRateHigh": 0,
            "PtcStartDate": '',
            "PtcEndDate": '',
            "TodayDate": "03/08/2024",
            "PublicName": ''
        },
        {
            "Utility": "RECO - Rockland Electric",
            "CommodityType": "E",
            "RateType": "Internal Green Fixed",
            "TaxRate": "RES",
            "State": "NJ",
            "RateCode": "ROCKLAND_NA_FIX013670R_12_ISC_000_N100_XX",
            "UtilityId": "RECO",
            "AccountNumberPattern": "^(\\d{10})$",
            "AccountNumberDescription": "10 Digit Account Number",
            "AccountNumberDescriptionSpanish": "Número de cuenta de 10 dígitos",
            "AccountNumberLabel": "Account Number",
            "UtilityPublicName": "Rockland Electric",
            "RateCodeType": "ISC_N_R_FIX",
            "TerritoryId": "RECO",
            "EnableForWebOverride": false,
            "ShowBudget": true,
            "UsageLimit": 0,
            "DailyRateValue": 0,
            "FlatRateValue": 0,
            "Index": 44,
            "SysId": 56040,
            "TerritorySysId": 43,
            "UtilityRateTypeSysId": 0,
            "InitialRate": 13.67,
            "InitialTerm": 12,
            "EnrollmentFee": 0,
            "CancellationFee": 0,
            "SecondaryRate": 0,
            "SecondaryTerm": 0,
            "MidRate": 0,
            "TotalTerm": 0,
            "TermLength": 12,
            "TermType": "Fixed",
            "Language": '',
            "Phone": "(800) 434-4100",
            "RateUnit": "kWh",
            "Budget": "Utility",
            "BudgetText": "Indra Energy does not offer Budget Billing in your area. If you are interested in Budget Billing, please contact your utility company.",
            "PtcUtil": '',
            "PtcRate": 0,
            "PtcRateLow": 0,
            "PtcRateHigh": 0,
            "PtcStartDate": '',
            "PtcEndDate": '',
            "TodayDate": "03/08/2024",
            "PublicName": ''
        },
        {
            "Utility": "ACE - Atlantic City Electric",
            "CommodityType": "E",
            "RateType": "Green Variable",
            "TaxRate": "RES",
            "State": "NJ",
            "RateCode": "ATLNCITY_NA_INTMONFEBR_02_ALL_COO_N100_XX",
            "UtilityId": "ACE",
            "AccountNumberPattern": "^(\\d{22})$",
            "AccountNumberDescription": "22 Digit Service Agreement Number",
            "AccountNumberDescriptionSpanish": "Número de acuerdo de servicio de 22 dígitos",
            "AccountNumberLabel": "Service Agreement Number",
            "UtilityPublicName": "Atlantic City Electric",
            "RateCodeType": "ALL_N_R_INT",
            "TerritoryId": "ACE",
            "EnableForWebOverride": true,
            "ShowBudget": true,
            "UsageLimit": 0,
            "DailyRateValue": 0,
            "FlatRateValue": 0,
            "Index": 105,
            "SysId": 55889,
            "TerritorySysId": 21,
            "UtilityRateTypeSysId": 0,
            "InitialRate": 10.9,
            "InitialTerm": 2,
            "EnrollmentFee": 0,
            "CancellationFee": 0,
            "SecondaryRate": 0,
            "SecondaryTerm": 0,
            "MidRate": 0.191,
            "TotalTerm": 0,
            "TermLength": 2,
            "TermType": "Variable",
            "Language": '',
            "Phone": "(800) 642-3780",
            "RateUnit": "kWh",
            "Budget": "Not available",
            "BudgetText": "Indra Energy does not offer Budget Billing in your area. If you are interested in Budget Billing, please contact your utility company.",
            "PtcUtil": '',
            "PtcRate": 0,
            "PtcRateLow": 0,
            "PtcRateHigh": 0,
            "PtcStartDate": '',
            "PtcEndDate": '',
            "TodayDate": "03/08/2024",
            "PublicName": ''
        },
        {
            "Utility": "JCP&L - Jersey Central Power and Light",
            "CommodityType": "E",
            "RateType": "Green Variable",
            "TaxRate": "RES",
            "State": "NJ",
            "RateCode": "JCPLELEC_NA_INTMONFEBR_02_ALL_COO_N100_XX",
            "UtilityId": "JCPL",
            "AccountNumberPattern": "^(080\\d{17})$",
            "AccountNumberDescription": "20 Digit Customer Number. Begins with 080.",
            "AccountNumberDescriptionSpanish": "Número de cliente de 20 dígitos. Empieza por 080.",
            "AccountNumberLabel": "Customer Number",
            "UtilityPublicName": "JCP&L",
            "RateCodeType": "ALL_N_R_INT",
            "TerritoryId": "JCPLE",
            "EnableForWebOverride": true,
            "ShowBudget": true,
            "UsageLimit": 0,
            "DailyRateValue": 0,
            "FlatRateValue": 0,
            "Index": 106,
            "SysId": 55890,
            "TerritorySysId": 33,
            "UtilityRateTypeSysId": 0,
            "InitialRate": 8.4,
            "InitialTerm": 2,
            "EnrollmentFee": 0,
            "CancellationFee": 0,
            "SecondaryRate": 0,
            "SecondaryTerm": 0,
            "MidRate": 0.178,
            "TotalTerm": 0,
            "TermLength": 2,
            "TermType": "Variable",
            "Language": '',
            "Phone": "(800) 662-3115",
            "RateUnit": "kWh",
            "Budget": "In house",
            "BudgetText": "I would like to participate in budget billing for my [electric_gas] supply charges.",
            "PtcUtil": '',
            "PtcRate": 0,
            "PtcRateLow": 0,
            "PtcRateHigh": 0,
            "PtcStartDate": '',
            "PtcEndDate": '',
            "TodayDate": "03/08/2024",
            "PublicName": ''
        },
        {
            "Utility": "PSEG - Public Service Electric and Gas",
            "CommodityType": "E",
            "RateType": "Green Variable",
            "TaxRate": "RES",
            "State": "NJ",
            "RateCode": "PSEG-ELE_NA_INTMONFEBR_02_ALL_COO_N100_XX",
            "UtilityId": "PSEG",
            "AccountNumberPattern": "^(PE\\d{18})$",
            "AccountNumberDescription": "20 Digit POD ID Number. Electric begins with PE. (E.G PE123456789012345678)",
            "AccountNumberDescriptionSpanish": "Número de identificación del POD de 20 dígitos. Electric comienza con PE. (Por ejemplo, PE123456789012345678)",
            "AccountNumberLabel": "POD ID Number",
            "UtilityPublicName": "PSEG",
            "RateCodeType": "ALL_N_R_INT",
            "TerritoryId": "PSEGE",
            "EnableForWebOverride": true,
            "ShowBudget": true,
            "UsageLimit": 0,
            "DailyRateValue": 0,
            "FlatRateValue": 0,
            "Index": 107,
            "SysId": 55891,
            "TerritorySysId": 42,
            "UtilityRateTypeSysId": 0,
            "InitialRate": 12.4,
            "InitialTerm": 2,
            "EnrollmentFee": 0,
            "CancellationFee": 0,
            "SecondaryRate": 0,
            "SecondaryTerm": 0,
            "MidRate": 0.193,
            "TotalTerm": 0,
            "TermLength": 2,
            "TermType": "Variable",
            "Language": '',
            "Phone": "(800) 436-7734",
            "RateUnit": "kWh",
            "Budget": "In house",
            "BudgetText": "I would like to participate in budget billing for my [electric_gas] supply charges.",
            "PtcUtil": '',
            "PtcRate": 0,
            "PtcRateLow": 0,
            "PtcRateHigh": 0,
            "PtcStartDate": '',
            "PtcEndDate": '',
            "TodayDate": "03/08/2024",
            "PublicName": ''
        },
        {
            "Utility": "RECO - Rockland Electric",
            "CommodityType": "E",
            "RateType": "Green Variable",
            "TaxRate": "RES",
            "State": "NJ",
            "RateCode": "ROCKLAND_NA_INTMONFEBR_02_ALL_COO_N100_XX",
            "UtilityId": "RECO",
            "AccountNumberPattern": "^(\\d{10})$",
            "AccountNumberDescription": "10 Digit Account Number",
            "AccountNumberDescriptionSpanish": "Número de cuenta de 10 dígitos",
            "AccountNumberLabel": "Account Number",
            "UtilityPublicName": "Rockland Electric",
            "RateCodeType": "ALL_N_R_INT",
            "TerritoryId": "RECO",
            "EnableForWebOverride": true,
            "ShowBudget": true,
            "UsageLimit": 0,
            "DailyRateValue": 0,
            "FlatRateValue": 0,
            "Index": 108,
            "SysId": 55892,
            "TerritorySysId": 43,
            "UtilityRateTypeSysId": 0,
            "InitialRate": 9.9,
            "InitialTerm": 2,
            "EnrollmentFee": 0,
            "CancellationFee": 0,
            "SecondaryRate": 0,
            "SecondaryTerm": 0,
            "MidRate": 0.189,
            "TotalTerm": 0,
            "TermLength": 2,
            "TermType": "Variable",
            "Language": '',
            "Phone": "(800) 434-4100",
            "RateUnit": "kWh",
            "Budget": "Utility",
            "BudgetText": "Indra Energy does not offer Budget Billing in your area. If you are interested in Budget Billing, please contact your utility company.",
            "PtcUtil": '',
            "PtcRate": 0,
            "PtcRateLow": 0,
            "PtcRateHigh": 0,
            "PtcStartDate": '',
            "PtcEndDate": '',
            "TodayDate": "03/08/2024",
            "PublicName": ''
        }
    ],
    "IncentivePackages": [
        {
            "SysId": 2,
            "Code": "RWD50",
            "ClonedFrom": "RWD25",
            "Name": "50 Indra Reward Dollars",
            "Description": "Customers get 50 Indra Reward Dollars upon sign-up, and another 50 Reward Dollars each month thereafter for as long as they’re a customer",
            "Status": "Activated",
            "ManagedBy": "ETANG",
            "Notes": '',
            "PublicDescription": "50 Indra Reward Points awarded every month customer remains a customer in good standing with Indra Energy. Restrictions apply. For terms & conditions and more details on Indra Energy’s Rewards Program, please visit the following website https://www.indraenergyrewards.com/#terms",
            "PublicDescriptionSpanish": "50 Puntos de Indra Rewards otorgados cada mes que el cliente permanece como cliente de Indra Energy. Aplican términos y condiciones. Aplican restricciones. Para conocer los términos y condiciones y más detalles sobre el Programa de Recompensas de Indra Energy, visite el siguiente sitio web https://www.indraenergyrewards.com/#spanish-terms",
            "PublicURL": "https://www.indraenergyrewards.com/#terms",
            "PublicURLSpanish": "https://www.indraenergyrewards.com/#spanish-terms",
            "ManualEligibility": false,
            "DateCreated": "2020-12-01T14:25:15.8584142",
            "UserId": "etang",
            "LastUpdated": "2021-02-23T17:06:30.0623716",
            "LastUserId": "etang",
            "Mode": '',
            "IsAltered": false,
            "IsDuplicate": false,
            "Logs": '',
            "Components": [
                {
                    "SysId": 2,
                    "PackageSysId": 2,
                    "IncentiveSysId": 2,
                    "Order": 1,
                    "RewardRules": "PENDINGCLOSE,ACTIVE,EMAILREQ,RESONLY",
                    "ExcludedStates": [],
                    "FulfilledBy": "OP",
                    "Schedule": "MT",
                    "NumDays": 45,
                    "FromDate": "Service Start Date",
                    "Limit": 0,
                    "LimitUnit":'',
                    "FirstSchedule":'',
                    "NumDaysFirstSchedule": 0,
                    "FromDateFirstSchedule": '',
                    "LimitFirstSchedule": '',
                    "LimitUnitFirstSchedule": '',
                    "SecondSchedule": '',
                    "NumDaysSecondSchedule": 0,
                    "FromDateSecondSchedule": '',
                    "LimitSecondSchedule": '',
                    "LimitUnitSecondSchedule": '',
                    "MinUsageElectric": 0,
                    "MinUsageGas": 0,
                    "IncentiveCode": '',
                    "RewardType": '',
                    "RulesList": [
                        "PENDINGCLOSE",
                        "ACTIVE",
                        "EMAILREQ",
                        "RESONLY"
                    ],
                    "ExcludedStatesList": []
                }
            ],
            "Errored": false,
            "Errors": {},
            "PageSize": 100,
            "PageNumber": 1,
            "SkipRows": 0,
            "IsQuery": false,
            "IsModified": false,
            "SpaOptions": '',
        }
    ],
    "IncentivePublicNotes": {
        "RP50PT": "50 MyEnergyPerks® Dollars"
    },
}